import{a as u,S as q,i as s}from"./assets/vendor-S2qh7U4E.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const P="56849530-efb256dcdb458a1eb8b8e9822";u.defaults.baseURL="https://pixabay.com/api/";async function f(r,t){return(await u.get("",{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".load-more");let M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const t=r.map(({webformatURL:a,largeImageURL:l,tags:e,likes:o,views:i,comments:S,downloads:v})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${l}">
        <img class="gallery-image" src="${a}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b> ${o}</p>
        <p class="info-item"><b>Views</b> ${i}</p>
        <p class="info-item"><b>Comments</b> ${S}</p>
        <p class="info-item"><b>Downloads</b> ${v}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function R(){h.innerHTML=""}function y(){m.classList.remove("hidden")}function b(){m.classList.add("hidden")}function L(){g.classList.remove("hidden")}function w(){g.classList.add("hidden")}const $=document.querySelector(".search-form"),B=document.querySelector(".load-more");let c="",n=1,d=0;$.addEventListener("submit",E);B.addEventListener("click",O);async function E(r){r.preventDefault();const t=r.currentTarget.elements.searchQuery.value.trim();if(!t){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}c=t,n=1,R(),w(),y();try{const a=await f(c,n);if(d=a.totalHits,a.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(a.hits),d>15?L():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}}async function O(){n+=1,w(),y();try{const r=await f(c,n);p(r.hits),x();const t=Math.ceil(d/15);n>=t?s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):L()}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}}function x(){const r=document.querySelector(".gallery-item");if(r){const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
